### ISSUE TITLE
Backpropagation-based Anomaly Explanation

### ISSUE THREAD

**Issue by eschalck** [Choubo/deviation-network-image#1]
Hello,
Thank you very much for the release, the code is very clean and the network is working well, with great results even on other datasets.
I was wondering if you also implemented the backpropagation-based anomaly explanation, as described in the paper, or if you could provide some further explanation about the method that was used to compute the heatmaps presented in the paper ?
Thank you, 
Kind regards,
Elsa

**Comment by Dongshengjiang** [comment]
same question, could you provide the code for computing the heatmap result?

**Comment by Choubo** [comment]
Sorry for the late reply. We already uploaded the code of anomaly explanation. Please check the newest version.

Kind regards,
Choubo
